name: Builder
on: [push]
jobs:
    build-win:
        runs-on: windows-latest
        steps:
          - name: Check out repository code
            uses: actions/checkout@v2
          - name: Install pyinstaller
            run: pip3 install pyinstaller
          - name: Install PyQT5
            run: pip3 install PyQt5
          - name: Build the executable
            run: pyinstaller --windowed main.py --onefile
          - uses: actions/upload-artifact@v2
            with: 
                name: build-windows
                path: dist/main.exe
