name: Builder
on: [push]
jobs:
    build-win:
        runs-on: windows-latest
        steps:
          - name: Check out repository code
            uses: actions/checkout@v2
          - name: Install the dependencies
            run: pip3 install pyinstaller
          - name: Build the executable
            run: pyinstaller --windowed main.py
          - uses: actions/download-artifact@v2
              with:
                path: dist/
    
          - name: Display structure of downloaded files
            run: ls -R
            working-directory: dist/
